language: node_js

node_js:
    - "14"
    - "12"
    - "10"

sudo: false

git:
    submodules: false


before_script:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver-v0.27.0-linux64.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver
    - npm install

script:
    - npm test

# after_success:
#     - npm run report-coveralls
#     - npm run report-codecovs
