language: node_js

node_js:
    - "node"
    - "14"
    - "12"
    - "10"
    - "8"

sudo: false

services:
    - sqlite3

git:
    submodules: false

before_script:
    - npm install


script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecovs
